# Version for Yuuki Asuna mod

find_package(Git REQUIRED)

if(NOT "${MOD_BUILD}" STREQUAL "Asuna")
    set(X265_BASE_BRANCH "bitbucket-git")
else()
    set(X265_BASE_BRANCH "old-stable")
endif()

execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_CLEAN_TAG
    RESULT_VARIABLE TAG_RESULT
    ERROR_VARIABLE TAG_ERROR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT "${TAG_RESULT}" STREQUAL "0")
    set(X265_CLEAN_TAG "unknown")
else()
    string(REPLACE "M" "" X265_LATEST_TAG "${X265_CLEAN_TAG}")
endif()

execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_HEAD_COMMIT_RAW
    RESULT_VARIABLE HEAD_RESULT
    ERROR_VARIABLE HEAD_ERROR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT "${HEAD_RESULT}" STREQUAL "0")
    set(X265_HEAD_COMMIT "unknown")
else()
    set(X265_HEAD_COMMIT "g${X265_HEAD_COMMIT_RAW}")
endif()

execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short origin/${X265_BASE_BRANCH}
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_BASE_COMMIT_RAW
    RESULT_VARIABLE BASE_RESULT
    ERROR_VARIABLE BASE_ERROR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT "${BASE_RESULT}" STREQUAL "0")
    set(X265_BASE_COMMIT "unknown")
else()
    set(X265_BASE_COMMIT "g${X265_BASE_COMMIT_RAW}")
endif()

execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-list --count ${X265_CLEAN_TAG}..HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_HEAD_DISTANCE
    RESULT_VARIABLE DISTANCE_RESULT
    ERROR_VARIABLE DISTANCE_ERROR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT "${DISTANCE_RESULT}" STREQUAL "0")
    set(X265_HEAD_DISTANCE "0")
endif()

execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-list --count ${X265_CLEAN_TAG}..origin/${X265_BASE_BRANCH}
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_BASE_DISTANCE
    RESULT_VARIABLE BASE_DISTANCE_RESULT
    ERROR_VARIABLE BASE_DISTANCE_ERROR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT "${BASE_DISTANCE_RESULT}" STREQUAL "0")
    set(X265_BASE_DISTANCE "0")
else()
endif()

if("${X265_HEAD_COMMIT}" STREQUAL "${X265_BASE_COMMIT}")
    set(X265_VERSION "${X265_LATEST_TAG}+${X265_BASE_DISTANCE}-${X265_BASE_COMMIT}")
else()
    if(X265_HEAD_DISTANCE MATCHES "^[0-9]+$" AND X265_BASE_DISTANCE MATCHES "^[0-9]+$")
        math(EXPR X265_VERSION_DIFF "${X265_HEAD_DISTANCE} - ${X265_BASE_DISTANCE}")
        set(X265_VERSION "${X265_LATEST_TAG}+${X265_BASE_DISTANCE}-${X265_BASE_COMMIT}+${X265_VERSION_DIFF}")
    else()
        set(X265_VERSION "${X265_LATEST_TAG}-${X265_HEAD_COMMIT}")
    endif()
endif()

set(X265_TAG_DISTANCE ${X265_BASE_DISTANCE})
message(STATUS "x265 Mod: ${MOD_BUILD}")
message(STATUS "x265 Release Version: ${X265_VERSION}")